# Set up public/private key pairs to protect the instance at launch time
# Public/private key pairs work by keeping the public key on the instance and the private key on your local workstation
- name: Generate key files
  user:
    name: "{{ ansible_env.USER }}"
    generate_ssh_key: yes
    ssh_key_file: .ssh/test_id_rsa
- name: Create OSP keypair
  os_keypair:
    cloud: ospcloud
    state: present
    name: ansible_ssh
    public_key_file: "{{ ansible_env.HOME }}/.ssh/test_id_rsa.pub"
